RunnerRegister/Models/Runner.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace RunnerRegister.Models
{
    public class Runner
    {
        [Key]
        public int Id { get; set; }
        [StringLength(100)]
        [Required]
        [Display(Name = "First Name")]
        public string FirstName { get; set; }
        [StringLength(100)]
        [Required]
        [Display(Name = "Last Name")]
        public string LastName { get; set; }
        [Required]
        [Display(Name = "Birth Date")]
        public DateTime BirthDate { get; set; }
        [Required]
        [Display(Name = "Gender")]
        public int GenderId { get; set; }
        public Gender Gender { get; set; }
        [StringLength(50)]
        [Required]
        public string Email { get; set; }
        [StringLength(15)]
        [Required]
        public string Telephone { get; set; }
        [StringLength(255)]
        [Required]
        public string Address { get; set; }
        [StringLength(50)]
        [Required]
        public string State { get; set; }
        [StringLength(15)]
        public string PostalCode { get; set; }
        [Display(Name = "Registration Date")]
        [Required]
        public DateTime RegistrationDate { get; set; }
        [Display(Name = "Country")]
        [Required]
        public int CountryId { get; set; }
        public Country Country { get; set; }
        [Display(Name = "Contact Name")]
        [Required]
        public string ContactName { get; set; }
        [Display(Name = "Contact Telephone")]
        [Required]
        public string ContactTelephone { get; set; }
        [Display(Name = "Event Name")]
        [Required]
        public int EventId { get; set; }
        public Event Event { get; set; }
    }
}

RunnerRegister/Models/RunnerViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace RunnerRegister.Models
{
    public class RunnerViewModel
    {
        [Key]
        public int Id { get; set; }
        [Display(Name = "First Name")]
        public string FirstName { get; set; }
        [Display(Name = "Last Name")]
        public string LastName { get; set; }
        [Display(Name = "Birth Date")]
        public DateTime BirthDate { get; set; }
        [Display(Name = "Gender")]
        public int GenderId { get; set; }
        public Gender Gender { get; set; }
        public string Email { get; set; }
        public string Telephone { get; set; }
        public string Address { get; set; }
        public string State { get; set; }
        public string PostalCode { get; set; }
        [Display(Name = "Registration Date")]
        public DateTime RegistrationDate { get; set; }
        public int CountryId { get; set; }
        public Country Country { get; set; }
        [Display(Name = "Contact Name")]
        public string ContactName { get; set; }
        [Display(Name = "Contact Telephone")]
        public string ContactTelephone { get; set; }
        [Display(Name = "Event Name")]
        public int EventId { get; set; }
        public Event Event { get; set; }
    }
}

RunnerRegister/Controllers/RunnersController.cs
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Migrations;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using System.Web.UI;
using AutoMapper;
using PagedList;
using RunnerRegister.Models;

namespace RunnerRegister.Controllers
{
    public class RunnersController : Controller
    {
        private readonly ApplicationDbContext db = new ApplicationDbContext();

        // GET: Runners
        public ActionResult Index(string sortDir, string searchInput, string currentFilter, int? page, string sortOrder = "")
        {
            if (searchInput != null)
                page = 1;
            else
                searchInput = currentFilter;

            ViewBag.CurrentFilter = searchInput;
            ViewBag.sortOrder = sortOrder;
            ViewBag.sortDir = sortDir;

            var runners = db.Runners.AsQueryable().Include(r => r.Event).Include(r => r.Gender).Include(r => r.Country);
            int pageSize = 5;
            int pageNumber = page ?? 1;
            string para = Request.QueryString["page"];
            if (string.IsNullOrEmpty(para))
            {
                Mapper.CreateMap<Runner, RunnerViewModel>();
                var runnerVms1 = Mapper.Map<List<Runner>, IEnumerable<RunnerViewModel>>(runners.ToList());
                var data1 = runnerVms1.ToPagedList(pageNumber, pageSize);

                return this.View(data1);
            }

            if (!string.IsNullOrEmpty(searchInput))
                runners = runners.Where(r => r.FirstName.ToLower().Contains(searchInput.ToLower()) || r.LastName.ToLower().Contains(searchInput.ToLower()));

            switch (sortOrder.ToLower())
            {
                case "name":
                    if (sortDir.ToLower() == "desc")
                        runners = runners.OrderByDescending(r => r.FirstName + r.LastName);
                    else
                        runners = runners.OrderBy(r => r.FirstName + r.LastName);
                    break;
                case "gender":
                    if (sortDir.ToLower() == "desc")
                        runners = runners.OrderByDescending(r => r.Gender.GenderType);
                    else
                        runners = runners.OrderBy(r => r.Gender.GenderType);
                    break;
                case "email":
                    if (sortDir.ToLower() == "desc")
                        runners = runners.OrderByDescending(r => r.Email);
                    else
                        runners = runners.OrderBy(r => r.Email);
                    break;
                case "telephone":
                    if (sortDir.ToLower() == "desc")
                        runners = runners.OrderByDescending(r => r.Telephone);
                    else
                        runners = runners.OrderBy(r => r.Telephone);
                    break;
                case "eventname":
                    if (sortDir.ToLower() == "desc")
                        runners = runners.OrderByDescending(r => r.Event.Name);
                    else
                        runners = runners.OrderBy(r => r.Event.Name);
                    break;
                case "eventstatus":
                    if (sortDir.ToLower() == "desc")
                        runners = runners.OrderByDescending(r => r.Event.IsClosed);
                    else
                        runners = runners.OrderBy(r => r.Event.IsClosed);
                    break;
                default:
                    runners = runners.OrderBy(r => r.FirstName + r.LastName);
                    break;
            }
            
            Mapper.CreateMap<Runner, RunnerViewModel>();
            var runnerVms = Mapper.Map<List<Runner>, IEnumerable<RunnerViewModel>>(runners.ToList());
            var data = runnerVms.ToPagedList(pageNumber, pageSize);

            return this.PartialView("_RunnerView", data);
        }
        public ActionResult Search(string searchInput, int? page, string currentFilter)
        {
            if (searchInput != null)
                page = 1;
            else
                searchInput = currentFilter;

            ViewBag.CurrentFilter = searchInput;

            var result = db.Runners.AsQueryable().Include(r => r.Event).Include(r => r.Gender).Include(r => r.Country);
            if (!string.IsNullOrEmpty(searchInput))
                result = result.Where(r => r.FirstName.ToLower().Contains(searchInput.ToLower()) || r.LastName.ToLower().Contains(searchInput.ToLower()));

            int pageSize = 5;
            int pageNumber = page ?? 1;

            Mapper.CreateMap<Runner, RunnerViewModel>();
            var runnerVms = Mapper.Map<List<Runner>, IEnumerable<RunnerViewModel>>(result.ToList());
            var data = runnerVms.ToPagedList(pageNumber, pageSize);
            return this.PartialView("_RunnerView", data);
        }

        // GET: Runners/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var runners = db.Runners.Include(r => r.Event).Include(r => r.Gender).Include(r => r.Country);
            var runner = runners.FirstOrDefault(r => r.Id == id);
            if (runner == null) return HttpNotFound();
            return View(runner);
        }

        // GET: Runners/Create
        public ActionResult Create()
        {
            ViewBag.CountryId = new SelectList(db.Countries, "Id", "CountryName",0);
            ViewBag.EventId = new SelectList(db.Events, "Id", "Name",0);
            ViewBag.GenderId = new SelectList(db.Genders, "Id", "GenderType",0);
            return View();
        }

        // POST: Runners/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include =
                "Id,FirstName,LastName,BirthDate,GenderId,Email,Telephone,Address,State,PostalCode,RegistrationDate,CountryId,ContactName,ContactTelephone,EventId")]
            RunnerViewModel runnerVm)
        {
            if (ModelState.IsValid)
            {
                Mapper.CreateMap<RunnerViewModel, Runner>();
                var runner = Mapper.Map<Runner>(runnerVm);
                db.Runners.Add(runner);
                db.SaveChanges();
                ViewBag.CountryId = new SelectList(db.Countries, "Id", "CountryName", runner.CountryId);
                ViewBag.EventId = new SelectList(db.Events, "Id", "Name", runner.EventId);
                ViewBag.GenderId = new SelectList(db.Genders, "Id", "GenderType", runner.GenderId);
                return RedirectToAction("Index");
            }

            return View(runnerVm);
        }

        // GET: Runners/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var runner = db.Runners.Find(id);
            if (runner == null) return HttpNotFound();
            Mapper.CreateMap<Runner, RunnerViewModel>();
            var runnerVm = Mapper.Map<RunnerViewModel>(runner);
            ViewBag.CountryId = new SelectList(db.Countries, "Id", "CountryName", runner.CountryId);
            ViewBag.EventId = new SelectList(db.Events, "Id", "Name", runner.EventId);
            ViewBag.GenderId = new SelectList(db.Genders, "Id", "GenderType", runner.GenderId);
            return View(runnerVm);
        }

        // POST: Runners/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include =
                "Id,FirstName,LastName,BirthDate,GenderId,Email,Telephone,Address,State,PostalCode,RegistrationDate,CountryId,ContactName,ContactTelephone,EventId")]
            RunnerViewModel runnerVm)
        {
            if (ModelState.IsValid)
            {
                Mapper.CreateMap<RunnerViewModel, Runner>();
                var runner = Mapper.Map<Runner>(runnerVm);
                db.Runners.AddOrUpdate(runner);
                db.SaveChanges();
                ViewBag.CountryId = new SelectList(db.Countries, "Id", "CountryName", runner.CountryId);
                ViewBag.GenderId = new SelectList(db.Genders, "Id", "GenderType", runner.GenderId);
                ViewBag.EventId = new SelectList(db.Events, "Id", "Name", runner.EventId);
                return RedirectToAction("Index");
            }

            return View(runnerVm);
        }

        // GET: Runners/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var runner = db.Runners.Find(id);
            if (runner == null) return HttpNotFound();
            return View(runner);
        }

        // POST: Runners/Delete/5
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var runner = db.Runners.Find(id);
            db.Runners.Remove(runner);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing) db.Dispose();
            base.Dispose(disposing);
        }
    }
}

RunnerRegister/Views/Runners/Create.cshtml
@using RunnerRegister.Models
@model RunnerRegister.Models.RunnerViewModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "Runners", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{

    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Runner</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.BirthDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.BirthDate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.BirthDate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.GenderId, "Gender", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.GenderId, (SelectList)ViewBag.GenderId, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.GenderId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Telephone, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Telephone, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Telephone, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.State, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.State, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.State, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PostalCode, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.PostalCode, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.PostalCode, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.RegistrationDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.RegistrationDate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.RegistrationDate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CountryId, "CountryId", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.CountryId, (SelectList)ViewBag.CountryId, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.CountryId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ContactName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ContactName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ContactName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ContactTelephone, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ContactTelephone, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ContactTelephone, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.EventId, "EventId", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.EventId, (SelectList)ViewBag.EventId, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.EventId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

RunnerRegister/Views/Runners/Delete.cshtml
@model RunnerRegister.Models.Runner

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Runner</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Country.CountryName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Country.CountryName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Event.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Event.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BirthDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BirthDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Telephone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Telephone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.State)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.State)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PostalCode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PostalCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RegistrationDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RegistrationDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ContactName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ContactName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ContactTelephone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ContactTelephone)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

RunnerRegister/Views/Runners/Edit.cshtml
@model RunnerRegister.Models.RunnerViewModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "Runners", FormMethod.Post, new { @enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Runner</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BirthDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BirthDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BirthDate, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.GenderId, "Gender", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("GenderId", null, htmlAttributes: new { @class = "form-control" })
                @*@Html.DropDownListFor(model => model.GenderId, (SelectList)ViewBag.GenderId, htmlAttributes: new { @class = "form-control" })*@
                @Html.ValidationMessageFor(model => model.GenderId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Telephone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Telephone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Telephone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.State, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.State, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.State, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PostalCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PostalCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PostalCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RegistrationDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RegistrationDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RegistrationDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CountryId, "CountryId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CountryId", null, htmlAttributes: new { @class = "form-control" })
                @*@Html.DropDownListFor(model => model.CountryId, (SelectList)ViewBag.CountryId, ViewBag.CountryId.SelectedValue, htmlAttributes: new { @class = "form-control" })*@
                @Html.ValidationMessageFor(model => model.CountryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ContactName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ContactName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ContactName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ContactTelephone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ContactTelephone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ContactTelephone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EventId, "EventId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("EventId", null, htmlAttributes: new { @class = "form-control" })
                @*@Html.DropDownListFor(model => model.EventId, (SelectList)ViewBag.EventId, ViewBag.EventId.SelectedValue, htmlAttributes: new { @class = "form-control" })*@
                @Html.ValidationMessageFor(model => model.EventId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

RunnerRegister/Views/Runners/Index.cshtml
@using RunnerRegister.Helper
@model PagedList.IPagedList<RunnerRegister.Models.RunnerViewModel>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
@using (Ajax.BeginForm("Search", "Runners",
    new AjaxOptions()
    {
        HttpMethod = "POST",
        UpdateTargetId = "results",
        InsertionMode = InsertionMode.Replace
    }))
{
    <input type="text" name="searchInput" placeholder="Live Search"
           oninput="$('#searchForm').submit()" value="@ViewBag.CurrentFilter" />
    <input type="submit" value="Search" />
}
<div id="results">
    @Html.Partial("_RunnerView", Model)
</div>